language: node_js
node_js:
  - "lts/*"
cache: yarn
jobs:
  include:
    - stage: lint
      name: "Linting"
      script:
        - yarn lint
    - stage: test
      name: "Test"
      script:
        - yarn test
